guide/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$',                 views.TypeListView.as_view(), name='collapsed'),
    url(r'^(?P<stub>[-\w]+)$', views.TypeListView.as_view(), name='extended'),
    url(r'^pdf/(?P<pk>\d+)$',  views.document_view,          name='view-pdf'),
]

guide/models.py
from django.db   import models
from django.http import FileResponse
from django.urls import reverse

class ReferenceType(models.Model):
  """
  Model representing a category (e.g. Publication, Proceedings, Slides etc.).
  """
  name  = models.CharField(max_length=50,                help_text = "An item type e.g. Publication, Proceedings, Presentation etc.")
  title = models.TextField(max_length=200, default='',   help_text = "An item title as it should appear on the web.")
  order = models.PositiveIntegerField(default=0,         help_text = "The position of this type in the list.")
  decor = models.CharField(max_length=25,  default = '', help_text = "An item decoration unicode symbol.")
  
  class Meta:
    ordering = ["order"] # defines order of items
    
  def get_absolute_url(self):
    return ('%s' % self.name)

  def get_description(self):
    if   'Tuto' in self.name: return 'Materials for students: tutorials and textbooks on optics, etc.'
    elif 'Publ' in self.name: return 'Selected scientific papers that are most important to me personally.'
    elif 'Slid' in self.name: return 'A collection of slides I have ever prepared for conferences, workshops, seminars, etc.'
    elif 'Thes' in self.name: return 'Here are my qualification works.'
    elif 'Draf' in self.name: return 'Incomplete or unpublished studies which however I do not want to forget.'
    elif 'Soft' in self.name: return 'Here are the (Github) links to software projects developed by myself.'
    elif 'Link' in self.name: return 'Some other links to the resources that I visit sometimes.'
 
  def __str__(self):
    """
    String for representing the Model object (in Admin site etc.)
    """
    return self.name
       
       
class Reference(models.Model):
  """
  Model representing one reference item.
  """
  title   = models.CharField(max_length=300)
  summary = models.TextField(max_length=500, blank=True, null=True, help_text="A brief description of the reference")
  itype   = models.ForeignKey(ReferenceType, on_delete=models.SET_NULL, null=True)
  year    = models.PositiveIntegerField(default=1970, blank=True, null=True)
  upload  = models.FileField(upload_to='static/', default = '', blank=True, null=True)
  exturl  = models.URLField(default = '', blank=True, null=True)
  
  class Meta:
    ordering = ["-year", "title"]

  def get_absolute_url(self):
      """
      Returns the url to access a particular  instance.
      """
      if self.upload:
        return reverse('view-pdf', args=[str(self.id)])
      else:
        return self.exturl

  def __str__(self):
      """
      String for representing the Model object.
      """
      return self.title

guide/views.py
from django.views import generic 
from django.http import FileResponse
from .models import Reference, ReferenceType
#from django.urls import reverse #Used to generate URLs by reversing the URL patterns
#from django.shortcuts import get_object_or_404

class TypeListView(generic.ListView):
  model = ReferenceType

def document_view(request, pk):
  el = Reference.objects.get(id=pk)
  if el.upload:
    return FileResponse(open(str(el.upload), 'rb'))
  else:
    pass
  

guide/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  {% block title %}<title>Nickolai Muchnoi on the Web</title>{% endblock %}
  {% load static %}
  <link rel="icon" href="https://muchnoi.net/favicon.png" type="image/png">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  {% block metadescription %}{% endblock %}
  


<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(22956646, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/22956646" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

</head>

<body>
      {% block content %}{% endblock %}

<div class='wob end'>
<p align='center'>
&copy;&nbsp;2005-2022&nbsp;
<a href="mailto:%20Николай%20Мучной%20&lt;N.Yu.Muchnoi@inp.nsk.su&gt;?subject=Feedback%20from%20My%20Site">Николай Мучной</a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<!-- Yandex.Metrika informer -->
<a href="https://metrika.yandex.ru/stat/?id=22956646&amp;from=informer"
target="_blank" rel="nofollow"><img src="https://informer.yandex.ru/informer/22956646/3_0_2F302DFF_0F100DFF_1_pageviews"
style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" class="ym-advanced-informer" data-cid="22956646" data-lang="ru" align="center" /></a>
<!-- /Yandex.Metrika informer -->
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="mailto:%20Nickolai%20Muchnoi%20&lt;N.Yu.Muchnoi@inp.nsk.su&gt;?subject=Feedback%20from%20My%20Site">Nickolai Muchnoi</a>&nbsp;
&copy;&nbsp;2005-2022&nbsp;
</p>
</div>

</body>
</html>

guide/templates/guide/referencetype_list.html
{% extends "base_generic.html" %}
{% block metadescription %}
  {% for l in referencetype_list %}
        {% if l.name == view.kwargs.stub %}
        <meta name="description" content="{{ l.get_description }}"> 
        {% endif %}
  {% endfor %}

{% endblock %}

{% block content %}
<H1>&nbsp;</H1>
  {% if referencetype_list %}
     {% for l in referencetype_list %}
        <div class='wob'>
        {% if l.name == view.kwargs.stub %}
          <h2><font size="+2" color="#ffff00">{{ l.decor }}</font>  &nbsp; {{ l.title }}</h2>
          {% if l.reference_set.all %}
            <ul>
            {% for el in l.reference_set.all %}
                  <li><a href="{{ el.get_absolute_url }}" target="_blank">{{ el.title }}</a> 
		              {% if el.summary %} <br><i> {{el.summary}} </i> {% endif %} 
                  {% if el.year %} <span style="float:right">({{el.year}})</span> </li> {% endif %}
            {% endfor %}
            </ul>
          {% endif %}
        {% else %}
        <h2><font size="+2" color="#ffff00">{{ l.decor }}</font>  &nbsp; <a href="{{ l.get_absolute_url }}">{{ l.title }}</a></h2> 
        {% endif %}
        </div> 
      {% endfor %}

  {% else %}
      <p>There are no books in the library.</p>
  {% endif %} 
{% endblock %}